会場を株式会社インプレスに更新した
Suguru-hub/ichiyasaGitSample pull request #1
Opened 2024-09-07 23:14 UTC by Suguru-hub

### 変更内容
イベント開催会場を「株式会社インプレス」に更新いたしました。

### 背景
「株式会社インプレス」殿がイベント会場を提供してくださることになったため。

2024-09-11 11:22 UTC, Suguru-hub commented
確認いたしました。
問題ないのでマージいたします。

2024-09-16 05:51 UTC, Shibata-sub-hub requested changes
修正ありがとうございます。
１点指摘のコメントを追加したので、対応よろしくお願いいたします。

2024-09-16 05:51 UTC, Shibata-sub-hub commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
「株式会社インプレステクノロジー」と正式名称に修正ください。

2024-09-16 06:01 UTC, Suguru-hub commented
@Shibata-sub-hub 
修正したものをプッシュしたので、再度ご確認よろしくお願いいたします。

2024-09-16 06:05 UTC, Shibata-sub-hub approved these changes
ご対応ありがとうございます。
承認いたします。

2024-09-21 23:21 UTC, merged